name: Code Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['7.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pytest-cov
          pip install -r requirements.txt

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Run tests and generate coverage
        run: |
          coverage run -m unittest discover
          coverage xml -i
          coverage report -m

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
